### ISSUE TITLE
Addition of options allows for pwgen to ignore length

### ISSUE THREAD

**Issue by JCLindo10** [JCLindo10/password-manager#1]
Adding specials or numbers to a gen() call can make it ignore the length parameter. As an example, if one calls the gen() function with length=1 and specials and numbers enabled, the resultant password is 3 characters long. With length=1 and numbers enabled, the resultant password is 2 characters long.

Steps to reproduce: 

1. Call pwgen.gen(1, special_chars = True, numbers = True)

**Comment by tramey345** [comment]
fixed it 👍
